### ISSUE TITLE
Language string and unfinished feature "Run Standard Agents"

### ISSUE THREAD

**Issue by astridx** [GHSVS-de/plg_system_importfontsghsvs#6]
PLG_SYSTEM_IMPORTFONTSGHSVS_RUNSTANDARDAGENTS_DESC is missing.

![Plugins  System   ImportFonts by GHSVS de   Ortsgemeinde Gering   Ein schönes kleines Dorf auf dem Maifeld in der Ost Eifel   Administration](https://user-images.githubusercontent.com/9974686/71783953-471c9980-2fee-11ea-943f-f4c928d095ce.png)

**Comment by GHSVS-de** [comment]
Unfortunately, I see that the feature "Run Standard Agents" is not yet integrated in a user-friendly way. Originally, it was intended to mimic the way google-webfonts-helper.herokuapp.com works.

I lost sight of it then.

I just uploaded the (frustrating ;-) ) corresponding language strings. You can simply copy the language files from the master branch over it.
And apply the single change to file importfontsghsvs.php.
See commit https://github.com/GHSVS-de/plg_system_importfontsghsvs/commit/7311d15e48beef990e1686e58aea0e393c9b2e94

I labeled this issue "enhancement".

**Comment by GHSVS-de** [comment]
Removed feature "Run Standard Agents" with version 2020.01.09
